name: Publish DBFerry

on:
    push:
        branches:
            - master # Trigger only on merge to master

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11" # match your project Python

            - name: Install UV
              run: pip install uv

            - name: Install build dependencies
              run: pip install --upgrade build wheel twine

            - name: Build package
              run: uv build

            - name: Publish to PyPI
              env:
                  TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
                  TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
              run: twine upload dist/*
